ID = {
  CHARACTER_1 = 1,
  CHARACTER_2 = 1+8,
  CHARACTER_3 = 1+8*2,
  CHARACTER_4 = 1+8*3,
  FLOWER_1 = 3,
  FLOWER_2 = 4,
  FLOWER_3 = 3+8,
  FLOWER_4 = 4+8,
  GRASS_1 = 5,
  GRASS_2 = 6,
  FLOOR_1 = 5+8,
  FLOOR_2 = 6+8,
  SOIL_DRY = 3+8*2,
  SOIL_WET = 3+8*3,
  ITEM_WHEAT = 7,
  SEED_WHEAT = 8,
  CROP_WHEAT = 4+8*2,
  CROP_WHEAT_DONE = 8+8*2,
  ITEM_TOMATO = 7+8,
  SEED_TOMATO = 8+8,
  CROP_TOMATO = 4+8*3,
  CROP_TOMATO_DONE = 8+8*3,
  CURSOR = 1+8*6
}

CROPS = {
  [ID.SEED_WHEAT] = {
    ITEM = ID.ITEM_WHEAT,
    CROP = ID.CROP_WHEAT,
    DONE = ID.CROP_WHEAT_DONE
  },
  [ID.SEED_TOMATO] = {
    ITEM = ID.ITEM_TOMATO,
    CROP = ID.CROP_TOMATO,
    DONE = ID.CROP_TOMATO_DONE
  }
}
